import { test, expect,request } from '@playwright/test';
import { POManager } from '../PageObjects/POManager';
import { username,password,tagline, date, gender, firstname, lastname, houseaddress, phonenumber, income, saving, mortgageBal, debt, quotevalue, feet, inches, weight, marijuana, drinks, OptionYes, OptionNo, benfirstname, benlastname, bendob, benshare, passportno, cardname, cardnumber, expirydate, cvv, accountholdername, transitnumber, institutionnumber, accountnumber, bankname } from '../Utils/TestData';

test.describe('Tests as per page', async () => {

    test.beforeEach('Base test', async ({ page }) => {
        const pomanager = new POManager(page);
        const loginpage = pomanager.getLoginPage();
        await loginpage.navigateToURL();
        await loginpage.login(username, password);
        const dashboardpage = pomanager.getDashboardPage();
        await dashboardpage.acceptCookies();
        await dashboardpage.selectCACountry();
        await dashboardpage.navigateToTermLifeCA();
        const termlifeCApage = pomanager.getTermLifeCAPage();
        await termlifeCApage.getHeaderText(tagline);
        await termlifeCApage.clickApplyNowBtn();
    });

    // test('Premium Quote Page', async ({ page }) => {
    //     const pomanager = new POManager(page);
    //     /*const loginpage = pomanager.getLoginPage();
    //     await loginpage.navigateToURL();
    //     await loginpage.login(username, password);
    //     const dashboardpage = pomanager.getDashboardPage();
    //     await dashboardpage.acceptCookies();
    //     await dashboardpage.selectCACountry();
    //     await dashboardpage.navigateToTermLifeCA();
    //     const termlifeCApage = pomanager.getTermLifeCAPage();
    //     await termlifeCApage.getHeaderText(tagline);
    //     await termlifeCApage.clickApplyNowBtn();*/
    //     const premiunquotepage = pomanager.getPremiumQuotePage();
    //     await premiunquotepage.selectGender(sex);
    //     await premiunquotepage.enterDOB(date);
    //     await premiunquotepage.selectCadianCitizen();
    //     await premiunquotepage.selectNonSmoker();
    //     await premiunquotepage.clickGetQuoteBtn();
    //     await premiunquotepage.clickContinueBtn();
    // });

    // test('Pre Application Page', async ({ page }) => {
    //     const pomanager = new POManager(page);
    //     /*const loginpage = pomanager.getLoginPage();
    //     await loginpage.navigateToURL();
    //     await loginpage.login(username, password);
    //     const dashboardpage = pomanager.getDashboardPage();
    //     await dashboardpage.acceptCookies();
    //     await dashboardpage.selectCACountry();
    //     await dashboardpage.navigateToTermLifeCA();
    //     const termlifeCApage = pomanager.getTermLifeCAPage();
    //     await termlifeCApage.getHeaderText(tagline);
    //     await termlifeCApage.clickApplyNowBtn();*/
    //     const premiunquotepage = pomanager.getPremiumQuotePage();
    //     await premiunquotepage.selectGender(gender);
    //     await premiunquotepage.enterDOB(date);
    //     await premiunquotepage.selectCadianCitizen();
    //     await premiunquotepage.selectNonSmoker();
    //     await premiunquotepage.clickGetQuoteBtn();
    //     await premiunquotepage.clickContinueBtn();
    //     const preapplicationpage = pomanager.getPreApplicationPage();
    //     await preapplicationpage.acceptPopWindow();
    //     await preapplicationpage.enterFirstName(firstname);
    //     await preapplicationpage.enterLastName(lastname);
    //     await preapplicationpage.enterAddress(houseaddress);
    //     await preapplicationpage.enterPhoneNumber(phonenumber);
    //     await preapplicationpage.selectAnswerForQuestion3();
    //     await preapplicationpage.selectAnswerForQuestion4();
    //     await preapplicationpage.selectAnswerForQuestion5();
    //     await preapplicationpage.clickConitnueBtn();
    // });

    // test('Needs Assessment Page', async ({ page }) => {
    //     const pomanager = new POManager(page);
    //     /*const loginpage = pomanager.getLoginPage();
    //     await loginpage.navigateToURL();
    //     await loginpage.login(username, password);
    //     const dashboardpage = pomanager.getDashboardPage();
    //     await dashboardpage.acceptCookies();
    //     await dashboardpage.selectCACountry();
    //     await dashboardpage.navigateToTermLifeCA();
    //     const termlifeCApage = pomanager.getTermLifeCAPage();
    //     await termlifeCApage.getHeaderText(tagline);
    //     await termlifeCApage.clickApplyNowBtn();*/
    //     const premiunquotepage = pomanager.getPremiumQuotePage();
    //     await premiunquotepage.selectGender(gender);
    //     await premiunquotepage.enterDOB(date);
    //     await premiunquotepage.selectCadianCitizen();
    //     await premiunquotepage.selectNonSmoker();
    //     await premiunquotepage.clickGetQuoteBtn();
    //     await premiunquotepage.clickContinueBtn();
    //     const preapplicationpage = pomanager.getPreApplicationPage();
    //     await preapplicationpage.acceptPopWindow();
    //     await preapplicationpage.enterFirstName(firstname);
    //     await preapplicationpage.enterLastName(lastname);
    //     await preapplicationpage.enterAddress(houseaddress);
    //     await preapplicationpage.enterPhoneNumber(phonenumber);
    //     await preapplicationpage.selectAnswerForQuestion3();
    //     await preapplicationpage.selectAnswerForQuestion4();
    //     await preapplicationpage.selectAnswerForQuestion5();
    //     await preapplicationpage.clickConitnueBtn();
    //     const needsassessmentpage = pomanager.getNeedsAssessmentPage();
    //     await needsassessmentpage.enterGrossIncome(income,saving,mortgageBal,debt);
    //     await needsassessmentpage.clickContinueBtn();
    // });

    // test('Confirm Premium Page', async ({ page }) => {
    //     const pomanager = new POManager(page);
    //     /*const loginpage = pomanager.getLoginPage();
    //     await loginpage.navigateToURL();
    //     await loginpage.login(username, password);
    //     const dashboardpage = pomanager.getDashboardPage();
    //     await dashboardpage.acceptCookies();
    //     await dashboardpage.selectCACountry();
    //     await dashboardpage.navigateToTermLifeCA();
    //     const termlifeCApage = pomanager.getTermLifeCAPage();
    //     await termlifeCApage.getHeaderText(tagline);
    //     await termlifeCApage.clickApplyNowBtn();*/
    //     const premiunquotepage = pomanager.getPremiumQuotePage();
    //     await premiunquotepage.selectGender(gender);
    //     await premiunquotepage.enterDOB(date);
    //     await premiunquotepage.selectCadianCitizen();
    //     await premiunquotepage.selectNonSmoker();
    //     await premiunquotepage.clickGetQuoteBtn();
    //     await premiunquotepage.clickContinueBtn();
    //     const preapplicationpage = pomanager.getPreApplicationPage();
    //     await preapplicationpage.acceptPopWindow();
    //     await preapplicationpage.enterFirstName(firstname);
    //     await preapplicationpage.enterLastName(lastname);
    //     await preapplicationpage.enterAddress(houseaddress);
    //     await preapplicationpage.enterPhoneNumber(phonenumber);
    //     await preapplicationpage.selectAnswerForQuestion3();
    //     await preapplicationpage.selectAnswerForQuestion4();
    //     await preapplicationpage.selectAnswerForQuestion5();
    //     await preapplicationpage.clickConitnueBtn();
    //     const needsassessmentpage = pomanager.getNeedsAssessmentPage();
    //     await needsassessmentpage.enterGrossIncome(income,saving,mortgageBal,debt);
    //     await needsassessmentpage.clickContinueBtn();
    //     const confirmpremiumpage = pomanager.getConfirmPremiumPage();
    //     //expect(await confirmpremiumpage.comfirmQuoteValue()).toContain(quotevalue);
    //     await confirmpremiumpage.clickContinueBtn();
    // });

    // test('Lifestyle Questionnaire Page', async ({ page }) => {
    //     const pomanager = new POManager(page);
    //     /*const loginpage = pomanager.getLoginPage();
    //     await loginpage.navigateToURL();
    //     await loginpage.login(username, password);
    //     const dashboardpage = pomanager.getDashboardPage();
    //     await dashboardpage.acceptCookies();
    //     await dashboardpage.selectCACountry();
    //     await dashboardpage.navigateToTermLifeCA();
    //     const termlifeCApage = pomanager.getTermLifeCAPage();
    //     await termlifeCApage.getHeaderText(tagline);
    //     await termlifeCApage.clickApplyNowBtn();*/
    //     const premiunquotepage = pomanager.getPremiumQuotePage();
    //     await premiunquotepage.selectGender(gender);
    //     await premiunquotepage.enterDOB(date);
    //     await premiunquotepage.selectCadianCitizen();
    //     await premiunquotepage.selectNonSmoker();
    //     await premiunquotepage.clickGetQuoteBtn();
    //     await premiunquotepage.clickContinueBtn();
    //     const preapplicationpage = pomanager.getPreApplicationPage();
    //     await preapplicationpage.acceptPopWindow();
    //     await preapplicationpage.enterFirstName(firstname);
    //     await preapplicationpage.enterLastName(lastname);
    //     await preapplicationpage.enterAddress(houseaddress);
    //     await preapplicationpage.enterPhoneNumber(phonenumber);
    //     await preapplicationpage.selectAnswerForQuestion3();
    //     await preapplicationpage.selectAnswerForQuestion4();
    //     await preapplicationpage.selectAnswerForQuestion5();
    //     await preapplicationpage.clickConitnueBtn();
    //     const needsassessmentpage = pomanager.getNeedsAssessmentPage();
    //     await needsassessmentpage.enterGrossIncome(income,saving,mortgageBal,debt);
    //     await needsassessmentpage.clickContinueBtn();
    //     //const confirmpremiumpage = pomanager.getConfirmPremiumPage();
    //     expect(await confirmpremiumpage.comfirmQuoteValue()).toContain(quotevalue);
    //     await confirmpremiumpage.clickContinueBtn();
    //     const lifestylequestionnairepage = pomanager.getLifestyleQuestionnairePage();
    //     await lifestylequestionnairepage.enterHeight(feet, inches, weight);
    //     await lifestylequestionnairepage.selectAnswerForQuestion1();
    //     await lifestylequestionnairepage.selectAnswerForQuestion2();
    //     await lifestylequestionnairepage.selectAnswerForQuestion3();
    //     await lifestylequestionnairepage.selectAnswerForQuestion4();
    //     await lifestylequestionnairepage.selectAnswerForQuestion5();
    //     await lifestylequestionnairepage.enterDrinksValue(drinks);
    //     await lifestylequestionnairepage.selectAnswerForQuestion6();
    //     await lifestylequestionnairepage.selectAnswerForQuestion7();
    //     await lifestylequestionnairepage.selectAnswerForQuestion8();
    //     await lifestylequestionnairepage.clickContinueBtn();
    // });

    // test('Medical Questionnaire Pages', async ({ page }) => {
    //     const pomanager = new POManager(page);
    //     /*const loginpage = pomanager.getLoginPage();
    //     await loginpage.navigateToURL();
    //     await loginpage.login(username, password);
    //     const dashboardpage = pomanager.getDashboardPage();
    //     await dashboardpage.acceptCookies();
    //     await dashboardpage.selectCACountry();
    //     await dashboardpage.navigateToTermLifeCA();
    //     const termlifeCApage = pomanager.getTermLifeCAPage();
    //     await termlifeCApage.getHeaderText(tagline);
    //     await termlifeCApage.clickApplyNowBtn();*/
    //     const premiunquotepage = pomanager.getPremiumQuotePage();
    //     await premiunquotepage.selectGender(gender);
    //     await premiunquotepage.enterDOB(date);
    //     await premiunquotepage.selectCadianCitizen();
    //     await premiunquotepage.selectNonSmoker();
    //     await premiunquotepage.clickGetQuoteBtn();
    //     await premiunquotepage.clickContinueBtn();
    //     const preapplicationpage = pomanager.getPreApplicationPage();
    //     await preapplicationpage.acceptPopWindow();
    //     await preapplicationpage.enterFirstName(firstname);
    //     await preapplicationpage.enterLastName(lastname);
    //     await preapplicationpage.enterAddress(houseaddress);
    //     await preapplicationpage.enterPhoneNumber(phonenumber);
    //     await preapplicationpage.selectAnswerForQuestion3();
    //     await preapplicationpage.selectAnswerForQuestion4();
    //     await preapplicationpage.selectAnswerForQuestion5();
    //     await preapplicationpage.clickConitnueBtn();
    //     const needsassessmentpage = pomanager.getNeedsAssessmentPage();
    //     await needsassessmentpage.enterGrossIncome(income,saving,mortgageBal,debt);
    //     await needsassessmentpage.clickContinueBtn();
    //     const confirmpremiumpage = pomanager.getConfirmPremiumPage();
    //     await page.waitForTimeout(500); 
    //     //expect(await confirmpremiumpage.comfirmQuoteValue()).toContain(quotevalue);
    //     await confirmpremiumpage.clickContinueBtn();
    //     const lifestylequestionnairepage = pomanager.getLifestyleQuestionnairePage();
    //     await page.waitForTimeout(500); 
    //     await lifestylequestionnairepage.enterHeight(feet, inches, weight);
    //     await lifestylequestionnairepage.selectAnswerForQuestion1();
    //     await lifestylequestionnairepage.selectAnswerForQuestion2();
    //     await lifestylequestionnairepage.selectAnswerForQuestion3();
    //     await lifestylequestionnairepage.selectAnswerForQuestion4();
    //     await lifestylequestionnairepage.selectAnswerForQuestion5();
    //     await lifestylequestionnairepage.enterDrinksValue(drinks);
    //     await lifestylequestionnairepage.selectAnswerForQuestion6();
    //     await lifestylequestionnairepage.selectAnswerForQuestion7();
    //     await lifestylequestionnairepage.selectAnswerForQuestion8();
    //     await lifestylequestionnairepage.clickContinueBtn();
    //     const medicalquestionnaire1page = pomanager.getMedicalQuestionnaire1Page();
    //     await medicalquestionnaire1page.selectAnswerForQuestion1();
    //     await medicalquestionnaire1page.selectAnswerForQuestion2();
    //     await medicalquestionnaire1page.selectAnswerForQuestion3();
    //     await medicalquestionnaire1page.selectAnswerForQuestion4();
    //     await medicalquestionnaire1page.selectAnswerForQuestion5();
    //     await medicalquestionnaire1page.selectAnswerForQuestion6();
    //     await medicalquestionnaire1page.selectAnswerForQuestion7();
    //     await medicalquestionnaire1page.selectAnswerForQuestion8();
    //     await medicalquestionnaire1page.selectAnswerForQuestion9();
    //     await medicalquestionnaire1page.selectAnswerForQuestion10();
    //     await medicalquestionnaire1page.selectAnswerForQuestion11();
    //     await medicalquestionnaire1page.clickConitnueBtn();
    //     const medicalquestionnaire2page = pomanager.getMedicalQuestionnaire2Page();
    //     await medicalquestionnaire2page.selectAnswerForQuestion1();
    //     await medicalquestionnaire2page.selectAnswerForQuestion2();
    //     await medicalquestionnaire2page.selectAnswerForQuestion3();
    //     await medicalquestionnaire2page.selectAnswerForQuestion4();
    //     await medicalquestionnaire2page.selectAnswerForQuestion5();
    //     await medicalquestionnaire2page.selectAnswerForQuestion6();
    //     await medicalquestionnaire2page.selectAnswerForQuestion7();
    //     await medicalquestionnaire2page.clickConitnueBtn(); 
    // });

    // test('Review Your Answers Page', async ({ page }) => {
    //     const pomanager = new POManager(page);
    //     /*const loginpage = pomanager.getLoginPage();
    //     await loginpage.navigateToURL();
    //     await loginpage.login(username, password);
    //     const dashboardpage = pomanager.getDashboardPage();
    //     await dashboardpage.acceptCookies();
    //     await dashboardpage.selectCACountry();
    //     await dashboardpage.navigateToTermLifeCA();
    //     const termlifeCApage = pomanager.getTermLifeCAPage();
    //     await termlifeCApage.getHeaderText(tagline);
    //     await termlifeCApage.clickApplyNowBtn();*/
    //     const premiunquotepage = pomanager.getPremiumQuotePage();
    //     await premiunquotepage.selectGender(gender);
    //     await premiunquotepage.enterDOB(date);
    //     await premiunquotepage.selectCadianCitizen();
    //     await premiunquotepage.selectNonSmoker();
    //     await premiunquotepage.clickGetQuoteBtn();
    //     await premiunquotepage.clickContinueBtn();
    //     const preapplicationpage = pomanager.getPreApplicationPage();
    //     await preapplicationpage.acceptPopWindow();
    //     await preapplicationpage.enterFirstName(firstname);
    //     await preapplicationpage.enterLastName(lastname);
    //     await preapplicationpage.enterAddress(houseaddress);
    //     await preapplicationpage.enterPhoneNumber(phonenumber);
    //     await preapplicationpage.selectAnswerForQuestion3();
    //     await preapplicationpage.selectAnswerForQuestion4();
    //     await preapplicationpage.selectAnswerForQuestion5();
    //     await preapplicationpage.clickConitnueBtn();
    //     const needsassessmentpage = pomanager.getNeedsAssessmentPage();
    //     await needsassessmentpage.enterGrossIncome(income,saving,mortgageBal,debt);
    //     await needsassessmentpage.clickContinueBtn();
    //     const confirmpremiumpage = pomanager.getConfirmPremiumPage();
    //     //expect(await confirmpremiumpage.comfirmQuoteValue()).toContain(quotevalue);
    //     await confirmpremiumpage.clickContinueBtn();
    //     const lifestylequestionnairepage = pomanager.getLifestyleQuestionnairePage();
    //     await lifestylequestionnairepage.enterHeight(feet, inches, weight);
    //     await lifestylequestionnairepage.selectAnswerForQuestion1();
    //     await lifestylequestionnairepage.selectAnswerForQuestion2();
    //     await lifestylequestionnairepage.selectAnswerForQuestion3();
    //     await lifestylequestionnairepage.selectAnswerForQuestion4();
    //     await lifestylequestionnairepage.selectAnswerForQuestion5();
    //     await lifestylequestionnairepage.enterDrinksValue(drinks);
    //     await lifestylequestionnairepage.selectAnswerForQuestion6();
    //     await lifestylequestionnairepage.selectAnswerForQuestion7();
    //     await lifestylequestionnairepage.selectAnswerForQuestion8();
    //     await lifestylequestionnairepage.clickContinueBtn();
    //     const medicalquestionnaire1page = pomanager.getMedicalQuestionnaire1Page();
    //     await medicalquestionnaire1page.selectAnswerForQuestion1();
    //     await medicalquestionnaire1page.selectAnswerForQuestion2();
    //     await medicalquestionnaire1page.selectAnswerForQuestion3();
    //     await medicalquestionnaire1page.selectAnswerForQuestion4();
    //     await medicalquestionnaire1page.selectAnswerForQuestion5();
    //     await medicalquestionnaire1page.selectAnswerForQuestion6();
    //     await medicalquestionnaire1page.selectAnswerForQuestion7();
    //     await medicalquestionnaire1page.selectAnswerForQuestion8();
    //     await medicalquestionnaire1page.selectAnswerForQuestion9();
    //     await medicalquestionnaire1page.selectAnswerForQuestion10();
    //     await medicalquestionnaire1page.selectAnswerForQuestion11();
    //     await medicalquestionnaire1page.clickConitnueBtn();
    //     const medicalquestionnaire2page = pomanager.getMedicalQuestionnaire2Page();
    //     await medicalquestionnaire2page.selectAnswerForQuestion1();
    //     await medicalquestionnaire2page.selectAnswerForQuestion2();
    //     await medicalquestionnaire2page.selectAnswerForQuestion3();
    //     await medicalquestionnaire2page.selectAnswerForQuestion4();
    //     await medicalquestionnaire2page.selectAnswerForQuestion5();
    //     await medicalquestionnaire2page.selectAnswerForQuestion6();
    //     await medicalquestionnaire2page.selectAnswerForQuestion7();
    //     await medicalquestionnaire2page.clickConitnueBtn(); 
    //     const reviewyouranswerspage = pomanager.getReviewYourAnswersPage();
    //     reviewyouranswerspage.clickConitnueBtn();
    // });

    test('Test Case', async ({ page }) => {
        const pomanager = new POManager(page); 
        const premiunquotepage = pomanager.getPremiumQuotePage();
        await premiunquotepage.getQuoteValue(gender, date);
        await premiunquotepage.clickContinueBtn();
        const preapplicationpage = pomanager.getPreApplicationPage();
        await preapplicationpage.acceptPopWindow();
        await preapplicationpage.enterUserName(firstname, lastname);
        await preapplicationpage.enterAddress(houseaddress);
        await preapplicationpage.enterPhoneNumber(phonenumber);
        await preapplicationpage.selectAnswerForQuestion3();
        await preapplicationpage.selectAnswerForQuestion4();
        await preapplicationpage.selectAnswerForQuestion5();
        await preapplicationpage.clickConitnueBtn();
        const needsassessmentpage = pomanager.getNeedsAssessmentPage();
        await needsassessmentpage.enterGrossIncome(income,saving,mortgageBal,debt);
        await needsassessmentpage.clickContinueBtn();
        const confirmpremiumpage = pomanager.getConfirmPremiumPage();
        await page.waitForTimeout(500); 
        await confirmpremiumpage.clickContinueBtn();
        const lifestylequestionnairepage = pomanager.getLifestyleQuestionnairePage();
        await page.waitForTimeout(500); 
        await lifestylequestionnairepage.lifestyleQuestions(OptionNo, feet, inches, weight, drinks);
        await lifestylequestionnairepage.clickContinueBtn();
        const medicalquestionnaire1page = pomanager.getMedicalQuestionnaire1Page();
        await page.waitForTimeout(500);
        await medicalquestionnaire1page.medicalQuestionsPage1(OptionNo);
        await medicalquestionnaire1page.clickConitnueBtn();
        const medicalquestionnaire2page = pomanager.getMedicalQuestionnaire2Page();
        await page.waitForTimeout(500);
        await medicalquestionnaire2page.medcialQuestionsPage2(OptionNo);
        await medicalquestionnaire2page.clickConitnueBtn(); 
        const reviewyouranswerspage = pomanager.getReviewYourAnswersPage();
        await reviewyouranswerspage.clickConitnueBtn();
        const personalstatementpage = pomanager.getPersonalStatementPage();
        await personalstatementpage.clickCheckboxes();
        await personalstatementpage.clickAgreeBtn();

    });


    

});


