module.exports = {   
    
    username : "gagandeep.singla+autouser@trantorinc.com",
    password : "Test@1",
    tagline : "We’ve got what matters most covered.",
    date : "01/01/2000",
    gender : "Female",
    firstname : "Test",
    lastname : "Auto user",
    houseaddress : "110",
    phonenumber : "2222222222",
    income : "20000",
    saving : "0",
    mortgageBal : "0",
    debt : "0",
    quotevalue : "50.58",
    feet : "5",
    inches : "9",
    weight : "180",
    marijuana : "1",
    drinks : "2",
    OptionYes : "Yes",
    OptionNo : "No",

}
