module.exports = {   
    url : "https://blanket-development.web.app",
    urlLogin : "https://blanket-development.web.app/pages/login",
    urlRegister : "https://blanket-development.web.app/pages/register",
    username : "gagandeep.singla+autoqa1@trantorinc.com",
    password : "123456",
    adminuser : "tester_env_dev@blanket.com",
    adminpass : "123456",
    cookiestext : "We value your privacy  For us, cookies are more than just a sweet treat. They are essential to providing you with an optimal and customized online experience. These little bits of data let us adapt the content and ads you see, while analyzing our traffic to better meet your needs. Enjoy our website, knowing that we do our utmost to offer you a tasty online experience. Check out our privacy policy  for more information.",
    tagline : "We’ve got what matters most covered.",
    date : "01/01/2000",
    gender : "Female",
    firstname : "Test",
    lastname : "Auto user",
    houseaddress : "110",
    phonenumber : "2222222222",
    income : "20000",
    saving : "0",
    mortgageBal : "0",
    debt : "0",
    quotevalue : "50.58",
    feet : "5",
    inches : "9",
    weight : "180",
    marijuana : "7",
    drinks : "2",
    drinksKnock : "15",
    OptionYes : "Yes",
    OptionNo : "No",
    benfirstname : "Test", 
    benlastname : "Beneficiary", 
    bendob : "01/01/2010", 
    benshare : "100",
    passportno : "AB123456",
    healthno: "123456789",
    licenseno: "AA1234",
    cardname : "Teser User", 
    cardnumber : "4111 1111 1111 1111", 
    expirydate : "01/2027",
    cvv : "213",
    accountholdername : "Test User", 
    transitnumber : "001", 
    institutionnumber : "030800", 
    accountnumber : "1234567", 
    bankname : "CNB",
    needAssessmentApiData : {
        "data": {
            "userKey": "cUikvtqcHENWpy26Jlp7Qg5WBLi2",
            "grossIncome": 50004,
            "grossHouseholdIncome": 0,
            "savings": 0,
            "mortgageBalance": 0,
            "loanDebts": 0,
            "dob": "2001-01-01",
            "locale": "en"
        }
    },
    getCaPremiumData : {
        "data": {
        "gender": "M",
        "smoker": false,
        "age": 23,
        "product": 10,
        "amount": 1000000,
        "locale": "en"
        }
    }

}
