name: macOS Test Workflow
on:
  schedule:
    
jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print macOS version
      run: |
        echo "macOS Version:"
        sw_vers
