name: macOS Test Workflow
on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes for testing
jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print macOS version
      run: |
        echo "macOS Version:"
        sw_vers
